global using System.IdentityModel.Tokens.Jwt;
global using System.Net;
global using System.Security.Claims;
global using BCrypt.Net;
global using System.Text;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.IdentityModel.Tokens;
